export const FETCH_POSTS = 'FETCH_POSTS'
export const SET_POSTS = 'SET_POSTS'
export const GET_POSTS = 'GET_POSTS'

export const FETCH_POST_DETAILS = 'FETCH_POST_DETAILS'
export const SET_POST_DETAILS = 'SET_POST_DETAILS'
export const GET_POST_DETAILS = 'GET_POST_DETAILS'

export const FETCH_CREATE_POST = 'FETCH_CREATE_POST'
export const SET_CREATE_POST = 'SET_CREATE_POST'
export const GET_CREATE_POST = 'GET_CREATE_POST'

export const FETCH_UPDATE_POST = 'FETCH_UPDATE_POST'
export const SET_UPDATE_POST = 'SET_UPDATE_POST'
export const GET_UPDATE_POST = 'GET_UPDATE_POST'

export const FETCH_DELETE_POST = 'FETCH_DELETE_POST'
export const SET_DELETE_POST = 'SET_DELETE_POST'
export const GET_DELETE_POST = 'GET_DELETE_POST'
