export const FETCH_USERS = 'FETCH_USERS'
export const SET_USERS = 'SET_USERS'
export const GET_USERS = 'GET_USER_LOGIN'

export const SET_USERS_PAGINATION_OPTIONS = 'SET_USERS_PAGINATION_OPTIONS'
export const GET_USERS_PAGINATION_OPTIONS = 'GET_USERS_PAGINATION_OPTIONS'

export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS'
export const SET_USER_DETAILS = 'SET_USER_DETAILS'
export const GET_USER_DETAILS = 'GET_USER_DETAILS'

export const FETCH_CREATE_USER = 'FETCH_CREATE_USER'
export const SET_CREATE_USER = 'SET_CREATE_USER'
export const GET_CREATE_USER = 'GET_CREATE_USER'

export const FETCH_UPDATE_USER = 'FETCH_UPDATE_USER'
export const SET_UPDATE_USER = 'SET_UPDATE_USER'
export const GET_UPDATE_USER = 'GET_UPDATE_USER'

export const FETCH_DELETE_USER = 'FETCH_DELETE_USER'
export const SET_DELETE_USER = 'SET_DELETE_USER'
export const GET_DELETE_USER = 'GET_DELETE_USER'
